repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: semgrep
        name: Semgrep Security Scan
        entry: shopping-assistant/.venv/bin/semgrep scan --error --config shopping-assistant/.semgrep/rules.yaml
        language: system
        types: [python]
